#!/bin/bash

alias     ..="cd .."
alias    ...="cd ../.."
alias   ....="cd ../../.."
alias  .....="cd ../../../.."
alias ......="cd ../../../../.."

alias zotero="/opt/zotero/zotero"
alias nxopen="xdg-open"
alias foxitReader="/home/nishant/.software/foxitsoftware/foxitreader/FoxitReader > /dev/null 2>&1"

alias rank_cse_svn="svn log --quiet svn+ssh://nsharma@cse.unl.edu/var/www/svn/UAV | grep ^r | awk '{print \$3}' | sort | uniq -c | sort -rn | head -n 10  | cat -n"

alias msthesis="cd /home/nishant/vcs/2017-thesis-nsharma"

alias website_test="cd /home/nishant/vcs/nishant_sharma && jekyll serve --host 0.0.0.0"

alias connectAnvil="sudo openconnect anvil-vpn.unl.edu"
alias connectAnvilRos="ssh ubuntu@10.71.104.31"

alias androidVM="qemu-system-x86_64 -m 2048 -boot d -enable-kvm -smp 3 -net nic -net user -hda ~/android/android-marshmallow.img"

alias svnMeldDiff="svn diff --diff-cmd='meld'"

alias cp="rsync -avP"

alias watch_starwars="telnet towel.blinkenlights.nl"
