#!/bin/bash
#
# Author: Nishant Sharma <'nishants1994' at gmail>
#

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

# merge in defaults and keymaps
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# status bar
~/vcs/slstatus/slstatus &

# for locking/unlocking system
xscreensaver -no-splash &

# unlock ssh keys
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcsii,secrets,ssh)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO

while true
do
    dwm
done
