#!/bin/bash
# Bash aliases: need customs to be sourced
#
# Author: Nishant Sharma <'nishants1994' at gmail>

# shorthand to cd backwards
alias     ..="cd .."
alias    ...="cd ../.."
alias   ....="cd ../../.."
alias  .....="cd ../../../.."
alias ......="cd ../../../../.."

# command maps
alias l="ls;"
alias ll="ls -l;"
alias r="reset;"
alias e="exit;"
alias cp="rsync -avP --copy-links"
alias nxopen="xdg-open"
alias zotero="/opt/zotero/zotero"
alias clion='~/.IDE/clion/bin/clion.sh'

# git related remaps
alias gd="git diff"
alias gdc="git diff --cached"
alias gdt="git difftool"
alias gdtc="git difftool --cached"
alias bdd="gdt origin/develop"
alias bddfs="gdt origin/develop-full-stable"
alias gmt="git mergetool"
alias gfo="git fetch origin"
alias gfop="git fetch origin --prune"
alias gfod="git fetch origin develop"
alias gmod="git merge origin/develop"
alias grod="git rebase origin/develop -i"
alias gpod="git pull origin develop"
alias grb="git rebase -i"
alias gst="git status"
alias gstsh="git stash"
alias gbr="git branch"
alias gco="git checkout"
alias gaa="git add -A"
alias gaf="git add"
alias gcm="git commit"
# glg needs the following to be set
# git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glg="git lg"
alias glg1="git log -1"
alias glgd="git lg origin/develop"
alias grog="git log --graph --abbrev-commit --decorate --all --format=format:\"%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(dim white) - %an%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n %C(white)%s%C(reset)\""

alias gpl="git pull"
alias gph="git push"
alias gphf="git push --force-with-lease"
alias gfp="git fetch --prune"
alias grh="git reset --hard"

# shorthand for editing and sourcing files
alias vim="nvim"
alias sbashrc="source ~/.bashrc"
alias ebashrc="vim ~/.bashrc; sbashrc"
alias ecustoms="vim ~/vcs/dot_files/bash/customs; sbashrc"
alias ealias="vim ~/vcs/dot_files/bash/aliases; sbashrc"
alias efunctions="vim ~/vcs/dot_files/bash/functions; sbashrc"
alias evimrc="vim ~/.vimrc"
alias etmuxconf="vim ~/.tmux.conf"

# personal website on github uses jekyll. Related command
alias website_test="cd ~/vcs/nishant_sharma && jekyll serve --host 0.0.0.0"

alias watch_starwars="telnet towel.blinkenlights.nl"

alias whitenoise="play -n synth 24:00:00 whitenoise"
alias pinknoise="play -n synth 24:00:00 pinknoise"
alias brownnoise="play -n synth 24:00:00 brownnoise"

