#!/bin/bash
# customizations to bash. Also used to setup aliases and functions 
#
# Author: Nishant Sharma <'nishants1994' at gmail>

# history updates
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

export EDITOR="vim"

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

get_time() {
     date | awk '{print $4}' | cut -c 1-5
}

print_horizontal_line() {
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
}

#export PS1="\$(print_horizontal_line) > \$(get_time) \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "


RESET="\[\033[0m\]"
RED="\[\033[0;31m\]"
GREEN="\[\033[01;32m\]"
BLUE="\[\033[01;34m\]"
YELLOW="\[\033[0;33m\]"

function parse_git_branch_simple {
  PS_BRANCH=''
  PS_FILL=${PS_LINE:0:$COLUMNS}
  if [ -d .svn ]; then
    PS_BRANCH="(svn r$(svn info|awk '/Revision/{print $2}'))"
    return
  elif [ -f _FOSSIL_ -o -f .fslckout ]; then
    PS_BRANCH="(fossil $(fossil status|awk '/tags/{print $2}')) "
    return
  fi
  ref=$(git branch 2> /dev/null) || return
  PS_BRANCH="(git $(echo "$ref" | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')) "
}

PROMPT_COMMAND=parse_git_branch_simple
PS_LINE=`printf -- '-%.0s' {1..400}`
PS_FILL=${PS_LINE:0:$COLUMNS}
PS_INFO="$GREEN\!$RESET:$BLUE\w"
PS_GIT="$YELLOW\$PS_BRANCH"
PS_TIME="\[\033[\$((COLUMNS-10))G\] $RED[\t]"
export PS1="\${PS_FILL}\[\033[0G\]${PS_INFO} ${PS_TIME}\n${RESET}\$ "
#export PS1="\${PS_FILL}\[\033[0G\]${PS_INFO} ${PS_GIT}${PS_TIME}\n${RESET}\$ "


# enable colors
eval "`dircolors -b`"

# force ls to always use color and type indicators
alias ls='ls -hF --color=auto'

# make the dir command work kinda like in windows (long format)
alias dir='ls --color=auto --format=long'

# make grep highlight results using color
export GREP_OPTIONS='--color=auto'

# Add some colour to LESS/MAN pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;33m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;42;30m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'

######### ONE TIME GIT SETTINGS ###############
#
# git config --global core.editor vimserv 
#
# git config --global diff.tool meld
# git config --global difftool.prompt false
# git config --global difftool.meld trustExitCode true
#
# git config --global merge.tool meld
# git config --global mergetool.prompt false
# git config --global mergetool.meld trustExitCode true
#
# git config --global user.name "Nishant Sharma"
# git config --global user.email <email>
#
#  git config --global mergetool.keepBackup false

